Central_System/Central_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cp_handler.urls'))
    # path( hostname/port/smartphoneID/chargepointId/currentPower)
]

Central_System/cp_handler/urls.py
from django.urls import path

from .views import index, chargepoint, chargepoint_detail, chargepoint_json, id_tag_info_json, call_reset

urlpatterns = [
    path('', index),
    path('chargepoint/', chargepoint),
    path('chargepoint/<str:slug>/', chargepoint_detail),
    path('cp/<str:slug>/', chargepoint_json),
    path('idtaginfo/', id_tag_info_json),
    path('call/call_reset/<str:cp_id>', call_reset)
]

Central_System/cp_handler/models/models.py
from django.db import models
from django.utils import timezone
from datetime import date


#from .. cp_handler import enums
#from .. cp_handler import models as m
from ocpp_d.v16.enums import AuthorizationStatus

from enums import enums

"""
the foreign key must be part of the object B if relationship A - B = 1 : N
"""


class ChargingStation(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    name = models.CharField(max_length=256)
    position = models.TextField(null=True, blank=True)
    phase_rotation = models.CharField(max_length=3, choices=enums.PhaseRotation.choices,
                                      default=enums.PhaseRotation.RST)
    installation_date = models.DateTimeField()
    max_current = models.FloatField(max_length=6, default=16.0)
    # operating_status =

    def __str__(self):
        return "{0}".format(self.name)


# ChargePoint represents the communication domain
class ChargePoint(models.Model):
    charging_station = models.ForeignKey(to='ChargingStation', on_delete=models.CASCADE)
    id = models.IntegerField(primary_key=True, unique=True)
    name = models.CharField(max_length=256)
    slug = models.SlugField(unique=True)
    # ToDo add enums
    # registration_status = models.CharField(max_length=128)
    # availability_status = models.CharField(max_length=128)
    max_power = models.IntegerField(default=11000)
    protocol = models.CharField(max_length=10, choices=enums.BackendProtocol.choices,
                                default=enums.BackendProtocol.OCPP16_J)
    charge_point_model = models.CharField(max_length=128)
    charge_point_vendor = models.CharField(max_length=256)

    def __str__(self):
        return "{0}: {1}".format(self.charging_station.name, self.name)


class Connector(models.Model):
    charge_point = models.ForeignKey(to='ChargePoint', on_delete=models.CASCADE)
    id = models.IntegerField(primary_key=True, default=0)
    socket_type = models.CharField(max_length=4, choices=enums.SocketType.choices,default=enums.SocketType.TYP2)
    max_current = models.FloatField(max_length=6, default=16.0)
    set_power_limit = models.IntegerField(default=11000)
    phase_rotation = models.CharField(max_length=3, choices=enums.PhaseRotation.choices,
                                      default=enums.PhaseRotation.RST)


class ChargePointConfiguration(models.Model):
    charge_point = models.ForeignKey(to='ChargePoint', on_delete=models.CASCADE)


class IdTag(models.Model):
    id_tag = models.CharField(max_length=20, default="0000000000000000")
    in_use = models.BooleanField(default=False)

    def __str__(self):
        return "{0}".format(self.id_tag)




class IdTagInfo(models.Model):
    id_tag = models.OneToOneField(IdTag, on_delete=models.CASCADE, primary_key=True)
    #type = models.
    expiry_date = models.DateTimeField()
    parent_id_tag = models.CharField(max_length=20, default="AAAAAAAAAAAAAAAA")
    status = models.CharField(max_length=32, choices=AuthorizationStatus.choices(),
                                      default=AuthorizationStatus.accepted)

    def is_active(self):
        if timezone.now() <= self.expiry_date:
            return True
        else:
            return False

    def to_json(self):
        json = {"expiry_date": str(self.expiry_date),
                  "parent_id_tag": str(self.parent_id_tag),
                  "status": self.status}
        return json


class Transaction(models.Model):
    charge_point_id = models.IntegerField(default=0)
    connector_id = models.IntegerField(default=0)
    start_id_tag = models.OneToOneField(IdTag, on_delete=models.CASCADE, null=True, related_name='start_id')
    stop_id_tag = models.OneToOneField(IdTag, on_delete=models.CASCADE, blank=True, related_name='stop_id')
    start_time = models.DateTimeField(null=True)
    stop_time = models.DateTimeField(null=True)
    start_meter_value = models.FloatField(blank=True)
    stop_meter_value = models.FloatField(blank=True)
    energy_consumed = models.FloatField(blank=True)

Central_System/cp_handler/models/serializers.py
from ocpp_d.v16.enums import AuthorizationStatus
from rest_framework import serializers
from .models import ChargePoint, IdTagInfo, Connector


#from enumchoicefield import ChoiceEnum, EnumChoiceField

class ChargePointSerializer(serializers.ModelSerializer):

    class Meta:
        model = ChargePoint
        fields = '__all__'
        # fields = ('id', 'max_power')


class ConnectorSerializer(serializers.ModelSerializer):

    class Meta:
        model = Connector
        fields = '__all__'
        # fields = ('id', 'max_power')


class IdTagInfoSerializer(serializers.ModelSerializer):
    class Meta:
        model = IdTagInfo
        #expiry_date = serializers.DateTimeField(format="%Y-%m-%d %H:%M:%S")
        #fields = ('expiry_date', 'parent_id_tag', 'status')
        exclude = ['id_tag']

    #status = serializers.ChoiceField(AuthorizationStatus)
    #status = EnumChoiceField(enum_class=AuthorizationStatus)

Central_System/cp_handler/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render
from ocpp_d.v16 import call
from ocpp_d.v16.enums import ResetType

from rest_framework.renderers import JSONRenderer

from cp_handler.CPconsumer import consumer_map
from cp_handler.models.models import ChargePoint, Connector, IdTagInfo
from cp_handler.models.serializers import ChargePointSerializer, ConnectorSerializer, IdTagInfoSerializer


def index(request):
    return render(request, template_name='index.html', context={'text': 'Hello World'})


def chargepoint(request):
    context = {'chargepoints': ChargePoint.objects.all()}
    return render(request=request, template_name='cp_overview.html', context=context)


def chargepoint_detail(request, slug):
    chargepoint = ChargePoint.objects.get(slug=slug)
    context = {'chargepoint': chargepoint}
    return render(request=request, template_name='cp_details.html', context=context)


def chargepoint_json(request, slug):
    serializer = ChargePointSerializer(ChargePoint.objects.get(slug=slug))
    #serializer = ConnectorSerializer(Connector.objects.first())
    print("***: {0}".format(serializer.data))
    return JsonResponse(serializer.data)


def id_tag_info_json(request):
    serializer = IdTagInfoSerializer(IdTagInfo.objects.first())
    #data = json.dumps(serializer.data)
    print("***: {0}".format(serializer.data))
    #print("***: {0}".format(data))
    return JsonResponse(serializer.data)


async def call_reset(request, cp_id):
    _consumer = consumer_map.get_consumer(cp_id)
    print("send Reset-message to CP")
    payload = call.ResetPayload(type=ResetType.soft)
    print(payload)
    response = await _consumer._charge_point.call(payload)
    print(response)


"""
def message(request):
    context = {'message': ChargePoint.objects.all()}
    return render(request=request, template_name='cp_overview.html', context=context)
"""

Central_System/cp_handler/templates/cp_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>registered charge points</title>
    <style type="text/css">
        div.margin {
         margin-top: 40px;
        }
    </style>
</head>
<body>
    <div class="container margin">
        <h1>Ladestationen</h1>
        {% if chargepoints %}
        <ul>
            {% for chargepoint in chargepoints %}
            <li> Chargepoint: {{ chargepoint.name }}</li>
            <ul>
                <li> ChargePointId: {{ chargepoint.id }}</li>
                <li> max Power [W]: {{ chargepoint.max_power }}</li>
                <li> protocol: {{ chargepoint.protocol }}</li>
            </ul>
            <br />
            {% if chargepoint.connector_set.count > 0 %}
            <ul>
                {% for connector in chargepoint.connector_set.all %}
                    <li> ConnectorId: {{ connector.id }}</li>
                    <ul>
                        <li> ChargePointId: {{ connector.socket_type }}</li>
                        <li> max Current [A]: {{ connector.max_current }}</li>
                        <li> current Power limit [W]: {{ connector.set_power_limit }}</li>
                    </ul>
                {% endfor %}
            </ul>
            {% endif %}
            <br />
            {% endfor %}
        </ul>
        {% endif %}
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    </div>
</body>
</html>

Central_System/cp_handler/templates/cp_overview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>registered charge points</title>
    <style type="text/css">
        div.margin {
         margin-top: 40px;
        }
    </style>
</head>
<body>
    <div class="container margin">
        <h1>Ladestationen</h1>
        {% if chargepoints %}
        <ul>
            {% for chargepoint in chargepoints %}
            <li><a href=""> Chargepoint: {{ chargepoint.name }}</a></li>
            <ul>
                <li> ChargePointId: {{ chargepoint.id }}</li>
                <li> max Power [W]: {{ chargepoint.max_power }}</li>
                <li> protocol: {{ chargepoint.protocol }}</li>
            </ul>
            <br />
            {% if chargepoint.connector_set.count > 0 %}
            <ul>
                {% for connector in chargepoint.connector_set.all %}
                    <li> ConnectorId: {{ connector.id }}</li>
                    <ul>
                        <li> ChargePointId: {{ connector.socket_type }}</li>
                        <li> max Current [A]: {{ connector.max_current }}</li>
                        <li> current Power limit [W]: {{ connector.set_power_limit }}</li>
                    </ul>
                {% endfor %}
            </ul>
            {% endif %}
            <br />
            {% endfor %}
        </ul>
        {% endif %}
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    </div>
</body>
</html>

Central_System/cp_handler/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X_UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>OCPP with Websocket channel</title>
</head>
<body>

    <div class=container">
        <div class="row">
            <div class="col-6 mx-auto mt-5">

                <h1 id="app">{{ text }}</h1>

             </div>
        </div>
    </div>

    <script>
        var socket = new WebSocket('ws://localhost:8000/CP_1/');

        socket.onmessage = function(event){
            var data = JSON.parse(event.data);
            console.log(data);
            document.querySelector('#app').innerText = data.message;
        }

    </script>

</body>
</html>